# This module requires the following variable settings at the shell level:
# export ANSIBLE_HOST_KEY_CHECKING=False
# export VCA_USER='vca login user name' 
# export VCA_PASS='vca login user password'
# This module also requires the following role: https://github.com/jdauphant/ansible-role-nginx

# Note that some of the setup/configuration is specific to the OS templates being used in this example
# (CentOS 6.4 64bit as provided in the VMware catalog)
# If you attempt to use other templates you may need to tweak the playbook accordingly 

 
- hosts: localhost
  connection: local
  vars:
    instanceid: 'd90612e9-ee23-44f4-b49c-112202b608fc'
    admin_pass: 'Vmware123!'
    public_ip: "144.130.51.227"
    vdc: "mreferre"
    template: "CentOS64-64BIT"
    catalog: "Public Catalog"
    network: "default-routed-network"
    vmname: "VMdemo"
    networkmode: "pool"

  tasks:
   - vca_vapp:
       state: present
       operation: poweron
       instance_id: "{{ instanceid }}"
       vdc_name: "{{ vdc }}"
       catalog_name: "{{ catalog }}"
       template_name: "{{ template }}"
       vm_name: "{{ vmname }}"
       network_mode: "{{ networkmode }}"
       admin_password: '{{ admin_pass }}'
       network_name: "{{ network }}"

     register: myvm

   - debug: var=myvm

   - vca_nat:
       instance_id: "{{ instanceid }}"
       vdc_name: 'mreferre'
       state: present
       nat_rules: 
         - rule_type: DNAT
           original_ip: "{{ public_ip }}"
           translated_ip: "{{ myvm.vm_details.network_info.ip }}"
   - vca_fw:
       instance_id: '{{ instanceid }}'
       vdc_name: 'mreferre'
       state: present
       fw_rules:
         - description: "Allow all trafic to the public ip"
           source_ip: "Any"
           dest_ip: "{{ public_ip }}"
 

   - wait_for: host="{{ public_ip }}" port=22 state=started delay=5
 
   - add_host: name="{{ public_ip }}" groups=nginx ansible_ssh_pass="{{ admin_pass }}"
   
- hosts: nginx
  pre_tasks:
   - name: install epel-release 
     yum: name="{{ item }}" state=latest
     with_items:
      - epel-release
   - shell: sed -i "s/mirrorlist=https/mirrorlist=http/" /etc/yum.repos.d/epel.repo 

   - shell: service iptables stop

   - name: install  selinux
     yum: name="{{ item }}" state=latest
     with_items:
      - libselinux-python
      - git
  roles: 
   - role: nginx
     nginx_http_params:
       - sendfile "on"
       - access_log "/var/log/nginx/access.log"
     nginx_sites:
       default:
         - listen 80
         - location / { try_files $uri $uri/ /index.html; }
         - location /images/ { try_files $uri $uri/ /index.html; }
  post_tasks:
   - shell: rm -rf /usr/share/nginx/html/*
   - name: Pull application from the repository.
     git: repo=https://github.com/Dissimulate/Tearable-Cloth.git dest=/usr/share/nginx/html